### ISSUE TITLE
ICE: Links set to open in new window don't.

### ISSUE THREAD

**Issue by doobox** [doobox/DooboxBugTracker#16]
Suspect related to the way we pull the link attributes from any detected links wrapping the images. May just need to add the extra attribute or pull all attributes as an array.

**Comment by leifottosson** [comment]
Hi Gary, when are you planning the next version update? Would like to see this fixed. Thanks.

**Comment by doobox** [comment]
Hi there Leif,

Soon. Had a look at the time of adding the bug, but was not an easy fix.

Kind Regards
Gary Simpson
Doobox Software

====================================================================
 Website : http://www.doobox.co.uk  <http://www.doobox.co.uk/>
 Twitter : http://twitter.com/doobox  <http://twitter.com/doobox%20>
====================================================================
