### ISSUE TITLE
Map2 Problem

### ISSUE THREAD

**Issue by quietchat** [doobox/DooboxBugTracker#20]
I have Map2 in a single column stack on a relatively simple page design.  The single column stack displays when the page is loaded, but the map does not..  Oddly, depending on which browser I use, I get a slightly different result.  Firefox shows nothing.  Safari show a bar saying "Choose a location".  You can see this for yourself at the site I'm using for development, "frozenghost.net".  The page in question is "Join Us".  

I should add that Map2 appears to work perfectly in RapidWeaver preview.  I am developing using RW6 and Stacks 3.  You many notice the pages have been renamed to "php".  This, however, seems not to be an issue as I have also tested with them using the "html" extension.  

I'm sure this is some idiocy on my part, but I've tried everything of which I can think.  Time to ask the Pros.

**Comment by doobox** [comment]
When things work as expected in RW preview mode but fail to work as expected in the published page, it points at something going wrong in the publishing phase. Stacks has no control in this phase at all.

Things that tend to be the culprit..
Using third party FTP applications, not correctly set-up for your server.
Although other things may appear to be publishing correctly, it has been found time and time again that without fully understanding your server requirements and the FTP application settings, publishing often fails.

As always I recommend publishing with RW it's self.

**Comment by quietchat** [comment]
I wiped the host directory and published out of RW.  No joy.  Although I liked your idea, it’s not the problem.  Any other thoughts about causes that I could pursue?

By the way, thanks for the quick response.

**Comment by doobox** [comment]
No. Like I say, once the code has been exported publishing is in the hands of The publishing software (RW in this case). If it works in preview and published correctly it would work in any webkit based browser.

The only thing I'd suggest if you have not already is selecting the "republish all files" option in Rapidweaver.

**Comment by quietchat** [comment]
Waste no more time on this one.  I reloaded the Map2 stack, cleared the stack from the RW page, re-inserted it and published from RW.  It works.  Apparently, the Map2 stack got corrupted.  It happens to the best of us.

Thanks for your time and the advice about using the RW FTP.  I appreciate the response and regret I didn’t try to reload first.

**Comment by doobox** [comment]
No worries.
