### ISSUE TITLE
Superhero : Make the down arrow font awesome

### ISSUE THREAD

**Issue by doobox** [doobox/DooboxBugTracker#22]
Change the down arrow to an optional choice of suitable font awesome arrows.

**Comment by rolco** [comment]
here are some possible arrow suggestions, thanks
![arrows](https://cloud.githubusercontent.com/assets/16561126/12120252/02ca9d70-b39e-11e5-9802-6b37d409e0fe.jpg)

**Comment by doobox** [comment]
Awaiting the latest beta of Stacks to be released, resolves a bug that will allow this to be addressed in a better way.
