### ISSUE TITLE
Check Stack Enhancement request

### ISSUE THREAD

**Issue by halsteadb** [doobox/DooboxBugTracker#27]
It would be nice to be able to select unchecked boxes as icons as well for users to be able to print off a checklist from your website and perform the checking off themselves (i.e.: winter maintenance, Spring maintenance, Travel tips sheet, etc). This would make this Stack truly useful as long as the icons were printable as well. Yes, this could be done using a PDF download but a Stack would save the trouble of styling the PDF ;)

**Comment by doobox** [comment]
Outside the scope of the stack. Better suited to a purpose built stack that uses styled checkbox html elements. Closing, as this won't happen with this stack.

**Comment by halsteadb** [comment]
I didn't mean to have the ability to check empty boxes, I meant the ability to choose empty icons instead of just checked icons in the stack to make an offline printable checklist for people instead of the item already being shown as checked on print. Maybe this is a better explanation of the enhancement request?
